### ISSUE TITLE
Please include 'main' field in package.json

### ISSUE THREAD

**Issue by OzymandiasTheGreat** [wooorm/devlop#1]
This package is rather widely used and because it omits `main` in favor of `exports`,
every package using devlop cannot be used in react-native, and I guess other runtimes that
don't yet support `exports` field.
There's actually experimental support for `exports` field in react-native's bundler, metro.
However since it's experimental it tends to break a lot of other libraries and is disabled by
default.
Including `main` field pointing to prod bundle would broaden support without losing much,
if anything.

**Comment by wooorm** [comment]
Hi.
That’s a serious bug in `react-native`.
It’s not feasible for me to support tools that don’t support standards.
The symptom you see is here — the problem will occur with thousands of packages.
I think this really has to be fixed in `react-native`!
